accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path

from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
)


urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
    path(
        "<int:pk>/complete/",
        ProjectUpdateView.as_view(),
        name="complete_project",
    ),
]

tasks/urls.py
from django.urls import path
from tasks.views import TaskCreateView, TaskListView, TaskUpdateView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from accounts.views import signup

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("signup/", signup, name="signup2"),
    path("tasks/", include("tasks.urls")),
]

accounts/models.py
# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    image = models.URLField(null=True, blank=True)
    coaching_tips = models.URLField(null=True, blank=True)
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="projects"
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.conf import settings
from django.db import models

# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL


class Task(models.Model):
    name = models.CharField(max_length=200)
    skill_description = models.TextField(default="")
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        USER_MODEL,
        related_name="tasks",
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy

# Create your views here.
from projects.models import Project


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])


class ProjectUpdateView(UpdateView):
    model = Project
    template_name = "projects/update.html"
    fields = ["is_completed"]

    def get_success_url(self):
        return reverse_lazy("list_projects")

tasks/views.py
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from tasks.models import Task
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "skill_description", "project", "assignee"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.project.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(UpdateView):
    model = Task
    template_name = "tasks/update.html"
    fields = ["is_completed"]

    def get_success_url(self):
        return reverse_lazy("show_my_tasks")

projects/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Snowboard Tricks</title>
        <link rel="stylesheet" href="{% static 'css/projects.css' %}">
    </head>
    <body id='bg'
          style="background-image:url('{% static 'images\IMG_5309.jpg' %}');">
        <header>
            {% comment %} <img src="{% static 'images\IMG_5309.jpg' %}"> {% endcomment %}
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href ="{% url 'list_projects' %}">My Tricks</a>
                        </li>
                        <li>
                            <a href ="{% url 'show_my_tasks' %}">Skills</a>
                        </li>
                        <li>
                            <a href ="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href ="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href ="{% url 'signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            {% block content %}
            {% endblock content %}
        </main>
    </body>
</html>

projects/templates/projects/create.html
{% extends 'base.html' %}
{% block content %}
    <div class = "project-form">
        <h1>New Trick</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Submit</button>
        </form>
    </div>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load static %}
{% load markdownify %}
{% block content %}
    <div class = "project-form">
        <h1>{{ project.name }}</h1>
        <p>
            {{ project.description|markdownify }}
        </P>
        <img src = "{{ project.image }}"/>
        <h2>Skills Needed for Trick</h2>
        <p>
            <a href ="{% url 'create_task' %}">Add a new skill</a>
        </p>
        {% if object.tasks.all|length > 0 %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Skill Level</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tasks in object.tasks.all %}
                        <tr>
                            <td>{{ tasks.name }}</td>
                            <td>{{ tasks.skill_description }}</td>
                            <td>{{ tasks.is_completed|yesno:"send it, not gonna send it" }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>
                This trick has no skills to be learned
            </p>
        {% endif %}
    </div>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% block content %}
    <div class = "project-list">
        <h1>My Tricks</h1>
        <p>
            <a href = "{% url 'create_project' %}">Add New Trick</a>
        </p>
        {% if project_list|length is 0 %}
            <P>
                You are not assigned to any tricks
            </P>
        {% else %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Skills Needed for Trick</th>
                        <th>Coaching</th>
                        <th>Trick Mastery</th>
                    </tr>
                </thead>
                <tbody>
                    {% for project in project_list %}
                        <tr>
                            <td>
                                <a href="{% url 'show_project' project.id %}">{{ project.name }}</a>
                            </td>
                            <td>{{ project.tasks.all | length }}</td>
                            <td>
                                <a href= '{{ project.coaching_tips }}'>Tips</a>
                            </td>
                            <td>
                                {% if project.is_completed is False %}
                                    <form method="post" action="{% url 'complete_project' project.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True">
                                        <button>Jerry</button>
                                    </form>
                                {% else %}
                                    {{ project.is_completed|yesno:"Stomped, " }}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock content %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block content %}
    <div class = "task-form">
        <h1>Skill to be Learned</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Submit</button>
        </form>
    </div>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% block content %}
    <div class = "my-task-list">
        <h1 class = "text">Skills to Work On</h1>
        {% if task_list %}
            <table class = "text">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Skill Level</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in task_list %}
                        <tr>
                            <td>{{ task.name }}</td>
                            <td>{{ task.skill_description }}</td>
                            <td>
                                {% if task.is_completed is False %}
                                    <form method="post" action="{% url 'complete_task' task.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True">
                                        <button>Complete</button>
                                    </form>
                                {% else %}
                                    {{ task.is_completed|yesno:"send it, not gonna send it" }}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>
                You have no skills to learn
            </p>
        {% endif %}
    </div>
{% endblock content %}